// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtL69NNAy6qup2bniJFr7mZp3xbMVXDIw',
    appId: '1:125759958224:web:d9047da6127b24ea5142d5',
    messagingSenderId: '125759958224',
    projectId: 'career-next-93b81',
    authDomain: 'career-next-93b81.firebaseapp.com',
    storageBucket: 'career-next-93b81.firebasestorage.app',
    measurementId: 'G-F8GQ40YFS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUSL8Pg2Ap0JhnB1GsErPC6zmRoqCgf0s',
    appId: '1:125759958224:android:275a1442337b9e325142d5',
    messagingSenderId: '125759958224',
    projectId: 'career-next-93b81',
    storageBucket: 'career-next-93b81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTiKrqIJiye6y_KKiwAuDGMEl02t61Xa0',
    appId: '1:125759958224:ios:c57ac781e5582e125142d5',
    messagingSenderId: '125759958224',
    projectId: 'career-next-93b81',
    storageBucket: 'career-next-93b81.firebasestorage.app',
    iosBundleId: 'com.yourdomain.flutterTest4837428',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTiKrqIJiye6y_KKiwAuDGMEl02t61Xa0',
    appId: '1:125759958224:ios:c57ac781e5582e125142d5',
    messagingSenderId: '125759958224',
    projectId: 'career-next-93b81',
    storageBucket: 'career-next-93b81.firebasestorage.app',
    iosBundleId: 'com.yourdomain.flutterTest4837428',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtL69NNAy6qup2bniJFr7mZp3xbMVXDIw',
    appId: '1:125759958224:web:d9047da6127b24ea5142d5',
    messagingSenderId: '125759958224',
    projectId: 'career-next-93b81',
    authDomain: 'career-next-93b81.firebaseapp.com',
    storageBucket: 'career-next-93b81.firebasestorage.app',
    measurementId: 'G-F8GQ40YFS5',
  );

}